### ISSUE TITLE
Booting from Iso Images

### ISSUE THREAD

**Issue by melorium** [vitaly-kamluk/bitscout#13] opened 2017-09-11 12:51 UTC
Hi again.
I feel like I Pain in the ass.
But I must ask you the latest iso images I burn to USB fail in boot.

I did so many but now I'm stucked again.

I use 3 different ways to burn these usb but all fail right now.

Why is that do you think

![img_5831](https://user-images.githubusercontent.com/31001934/30275159-afbf8c2e-9700-11e7-9c24-dfc20f58b6d0.JPG)

**Comment by melorium** [comment] 2017-09-11 13:03
There are from the latest build where you put in EEFI support.

Do you think i did something wrong?

I can boot the isoimage when I use viritualbox on my Mac.


Dennis

**Comment by melorium** [comment] 2017-09-11 13:11
The older images work well. But since I try to use the build with EEFI support the images can't boot.
I use the "sudo dd if=./bitscout-16.04.iso of=/dev/sdX" command tl make the images.

Dennis

**Comment by vitaly-kamluk** [comment] 2017-09-11 13:50
Hi!
Lets see what's wrong. Please help me with some requests:
1. Did the same ISO work fine on VM on your Mac?
2. Please post the output of the following command on linux: `$ file ./bitscout-16.04.iso`

Also please use `$ git pull` to update the code before building to make sure you have the latest stable version.

**Comment by melorium** [comment] 2017-09-11 13:58
Yes I will do that.
The iso works on VM om Mac.
I did a new virtual Ubuntu 1 hour ago and used the new stable version and did same ISO files.
I did a small iso with the selection 1.
![skarmklipp 2017-09-11 15 57 34](https://user-images.githubusercontent.com/31001934/30278141-f8ff06fe-9709-11e7-8e96-3b8a1665cc47.png)

**Comment by melorium** [comment] 2017-09-11 14:00
And I use 3 different usb memory and the same machines to boot from.
They worked perfekt until yesterday when I read something of EEFI support.
Dennis

**Comment by vitaly-kamluk** [comment] 2017-09-11 14:20
Sorry, you may be right. It has to be better tested before moving to UEFI. I tested on few setups and it worked.
Let me rollback that change to keep the main branch stable.

**Comment by melorium** [comment] 2017-09-11 14:22
Yes please.
Tell me when you did that :)
I work with you software all day long.
Thanks again for all support.

**Comment by melorium** [comment] 2017-09-11 14:24
yes sorry I mean UEFI :)

Dennis

**Comment by melorium** [comment] 2017-09-11 16:31
Tell me when you down the rollback :)

**Comment by vitaly-kamluk** [comment] 2017-09-11 17:20
I realized that there was a bigger bug under that stone. I think it existed even before the UEFI patch.
I believe it's fixed now but would like to hear that from you.

Note, that UEFI boot method is still experimental, so use classic MBR (sometimes called CSM) boot method in BIOS for now.

**Comment by vitaly-kamluk** [comment] 2017-09-11 17:24
Please try the latest code and report if your problem is still there.

**Comment by melorium** [comment] 2017-09-11 17:38
Thanks again. Il try it now :)

**Comment by melorium** [comment] 2017-09-11 18:51
Yes :)
It works now with all my laptops.
Thanks Thanks. :)

Dennis

**Comment by vitaly-kamluk** [comment] 2017-09-12 02:06
Glad to hear that!
Your contribution with bug reports is really important, Dennis! Please keep finding more hidden bugs! :)
I started building automated testing scripts to make sure we don't get regression bugs and test all the components. It's in ./autotest.sh. You can try it after building the ISO. Of course it uses a VM, so there may be differences comparing to real hardware.
Closing this bug now. Open new one if you find more!

**Closed as completed by vitaly-kamluk** 2017-09-12 02:06 UTC

**Comment by melorium** [comment] 2017-09-12 10:52
Thanks.
Should I run autotest.sh within a container or on birscout making machine?
Il do my best to find bugs and but sometimes I feel like a scout to disturb you, but il try to understand it better. :)

Dennis

**Comment by vitaly-kamluk** [comment] 2017-09-12 12:06
You can run ./autotest.sh in the same directory where you build the ISO file. It will do some basic tests. If you edit this script and set VISIBLE=1 in it, you will be able to see what it is doing. It is automated so some input may be very fast but might be interesting and helpful for debugging if you work on improvements. In addition it's possible to see the VM console with remote-viewer app on the same machine. See the output of ./autotest.sh for exact commandline.

And, please, do not hesitate to start a conversation and submit bug reports. All your reports were valuable because they lead to some important findings and fixes. I have blind spots and sometimes don't see all the issues, so I really appreciate your help and feedback!
